"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Sport:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SportEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Sport.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPORT_UNSPECIFIED: _Sport.ValueType  # 0
    SPORT_MLB: _Sport.ValueType  # 1
    SPORT_NFL: _Sport.ValueType  # 2

class Sport(_Sport, metaclass=_SportEnumTypeWrapper): ...

SPORT_UNSPECIFIED: Sport.ValueType  # 0
SPORT_MLB: Sport.ValueType  # 1
SPORT_NFL: Sport.ValueType  # 2
Global___Sport: _TypeAlias = Sport  # noqa: Y015

class _EventType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EVENT_TYPE_UNSPECIFIED: _EventType.ValueType  # 0
    EVENT_TYPE_PITCH: _EventType.ValueType  # 1
    EVENT_TYPE_ATBAT_START: _EventType.ValueType  # 2
    EVENT_TYPE_ATBAT_END: _EventType.ValueType  # 3
    EVENT_TYPE_PICKOFF: _EventType.ValueType  # 4
    EVENT_TYPE_MOUND_VISIT: _EventType.ValueType  # 5
    EVENT_TYPE_PITCHING_CHANGE: _EventType.ValueType  # 6
    EVENT_TYPE_SUBSTITUTION: _EventType.ValueType  # 7
    EVENT_TYPE_DEFENSIVE_SHIFT: _EventType.ValueType  # 8
    EVENT_TYPE_INNING_STATE: _EventType.ValueType  # 9
    EVENT_TYPE_GAME_STATE: _EventType.ValueType  # 10
    EVENT_TYPE_NFL_PLAY: _EventType.ValueType  # 11

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper): ...

EVENT_TYPE_UNSPECIFIED: EventType.ValueType  # 0
EVENT_TYPE_PITCH: EventType.ValueType  # 1
EVENT_TYPE_ATBAT_START: EventType.ValueType  # 2
EVENT_TYPE_ATBAT_END: EventType.ValueType  # 3
EVENT_TYPE_PICKOFF: EventType.ValueType  # 4
EVENT_TYPE_MOUND_VISIT: EventType.ValueType  # 5
EVENT_TYPE_PITCHING_CHANGE: EventType.ValueType  # 6
EVENT_TYPE_SUBSTITUTION: EventType.ValueType  # 7
EVENT_TYPE_DEFENSIVE_SHIFT: EventType.ValueType  # 8
EVENT_TYPE_INNING_STATE: EventType.ValueType  # 9
EVENT_TYPE_GAME_STATE: EventType.ValueType  # 10
EVENT_TYPE_NFL_PLAY: EventType.ValueType  # 11
Global___EventType: _TypeAlias = EventType  # noqa: Y015

@_typing.final
class Spine(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    SPORT_FIELD_NUMBER: _builtins.int
    GAME_PK_FIELD_NUMBER: _builtins.int
    EVENT_TIME_FIELD_NUMBER: _builtins.int
    SOURCE_TIME_FIELD_NUMBER: _builtins.int
    INGEST_TIME_FIELD_NUMBER: _builtins.int
    event_id: _builtins.str
    event_type: Global___EventType.ValueType
    sport: Global___Sport.ValueType
    game_pk: _builtins.str
    @_builtins.property
    def event_time(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def source_time(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def ingest_time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        event_id: _builtins.str = ...,
        event_type: Global___EventType.ValueType = ...,
        sport: Global___Sport.ValueType = ...,
        game_pk: _builtins.str = ...,
        event_time: _timestamp_pb2.Timestamp | None = ...,
        source_time: _timestamp_pb2.Timestamp | None = ...,
        ingest_time: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event_time", b"event_time", "ingest_time", b"ingest_time", "source_time", b"source_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_id", b"event_id", "event_time", b"event_time", "event_type", b"event_type", "game_pk", b"game_pk", "ingest_time", b"ingest_time", "source_time", b"source_time", "sport", b"sport"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Spine: _TypeAlias = Spine  # noqa: Y015

@_typing.final
class MLBPitch(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPINE_FIELD_NUMBER: _builtins.int
    AT_BAT_INDEX_FIELD_NUMBER: _builtins.int
    PITCH_NUMBER_FIELD_NUMBER: _builtins.int
    INNING_FIELD_NUMBER: _builtins.int
    INNING_HALF_FIELD_NUMBER: _builtins.int
    BATTER_ID_FIELD_NUMBER: _builtins.int
    BATTER_NAME_FIELD_NUMBER: _builtins.int
    PITCHER_ID_FIELD_NUMBER: _builtins.int
    PITCHER_NAME_FIELD_NUMBER: _builtins.int
    PITCH_TYPE_FIELD_NUMBER: _builtins.int
    PITCH_TYPE_DESCRIPTION_FIELD_NUMBER: _builtins.int
    START_SPEED_MPH_FIELD_NUMBER: _builtins.int
    END_SPEED_MPH_FIELD_NUMBER: _builtins.int
    SPIN_RATE_RPM_FIELD_NUMBER: _builtins.int
    BALLS_FIELD_NUMBER: _builtins.int
    STRIKES_FIELD_NUMBER: _builtins.int
    OUTS_FIELD_NUMBER: _builtins.int
    CALL_CODE_FIELD_NUMBER: _builtins.int
    CALL_DESCRIPTION_FIELD_NUMBER: _builtins.int
    IS_IN_PLAY_FIELD_NUMBER: _builtins.int
    IS_STRIKE_FIELD_NUMBER: _builtins.int
    IS_BALL_FIELD_NUMBER: _builtins.int
    RAW_PAYLOAD_JSON_FIELD_NUMBER: _builtins.int
    at_bat_index: _builtins.int
    pitch_number: _builtins.int
    inning: _builtins.int
    inning_half: _builtins.str
    batter_id: _builtins.int
    batter_name: _builtins.str
    pitcher_id: _builtins.int
    pitcher_name: _builtins.str
    pitch_type: _builtins.str
    pitch_type_description: _builtins.str
    start_speed_mph: _builtins.float
    end_speed_mph: _builtins.float
    spin_rate_rpm: _builtins.float
    balls: _builtins.int
    strikes: _builtins.int
    outs: _builtins.int
    call_code: _builtins.str
    call_description: _builtins.str
    is_in_play: _builtins.bool
    is_strike: _builtins.bool
    is_ball: _builtins.bool
    raw_payload_json: _builtins.str
    @_builtins.property
    def spine(self) -> Global___Spine: ...
    def __init__(
        self,
        *,
        spine: Global___Spine | None = ...,
        at_bat_index: _builtins.int = ...,
        pitch_number: _builtins.int = ...,
        inning: _builtins.int | None = ...,
        inning_half: _builtins.str | None = ...,
        batter_id: _builtins.int | None = ...,
        batter_name: _builtins.str | None = ...,
        pitcher_id: _builtins.int | None = ...,
        pitcher_name: _builtins.str | None = ...,
        pitch_type: _builtins.str | None = ...,
        pitch_type_description: _builtins.str | None = ...,
        start_speed_mph: _builtins.float | None = ...,
        end_speed_mph: _builtins.float | None = ...,
        spin_rate_rpm: _builtins.float | None = ...,
        balls: _builtins.int | None = ...,
        strikes: _builtins.int | None = ...,
        outs: _builtins.int | None = ...,
        call_code: _builtins.str | None = ...,
        call_description: _builtins.str | None = ...,
        is_in_play: _builtins.bool | None = ...,
        is_strike: _builtins.bool | None = ...,
        is_ball: _builtins.bool | None = ...,
        raw_payload_json: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_balls", b"_balls", "_batter_id", b"_batter_id", "_batter_name", b"_batter_name", "_call_code", b"_call_code", "_call_description", b"_call_description", "_end_speed_mph", b"_end_speed_mph", "_inning", b"_inning", "_inning_half", b"_inning_half", "_is_ball", b"_is_ball", "_is_in_play", b"_is_in_play", "_is_strike", b"_is_strike", "_outs", b"_outs", "_pitch_type", b"_pitch_type", "_pitch_type_description", b"_pitch_type_description", "_pitcher_id", b"_pitcher_id", "_pitcher_name", b"_pitcher_name", "_raw_payload_json", b"_raw_payload_json", "_spin_rate_rpm", b"_spin_rate_rpm", "_start_speed_mph", b"_start_speed_mph", "_strikes", b"_strikes", "balls", b"balls", "batter_id", b"batter_id", "batter_name", b"batter_name", "call_code", b"call_code", "call_description", b"call_description", "end_speed_mph", b"end_speed_mph", "inning", b"inning", "inning_half", b"inning_half", "is_ball", b"is_ball", "is_in_play", b"is_in_play", "is_strike", b"is_strike", "outs", b"outs", "pitch_type", b"pitch_type", "pitch_type_description", b"pitch_type_description", "pitcher_id", b"pitcher_id", "pitcher_name", b"pitcher_name", "raw_payload_json", b"raw_payload_json", "spin_rate_rpm", b"spin_rate_rpm", "spine", b"spine", "start_speed_mph", b"start_speed_mph", "strikes", b"strikes"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_balls", b"_balls", "_batter_id", b"_batter_id", "_batter_name", b"_batter_name", "_call_code", b"_call_code", "_call_description", b"_call_description", "_end_speed_mph", b"_end_speed_mph", "_inning", b"_inning", "_inning_half", b"_inning_half", "_is_ball", b"_is_ball", "_is_in_play", b"_is_in_play", "_is_strike", b"_is_strike", "_outs", b"_outs", "_pitch_type", b"_pitch_type", "_pitch_type_description", b"_pitch_type_description", "_pitcher_id", b"_pitcher_id", "_pitcher_name", b"_pitcher_name", "_raw_payload_json", b"_raw_payload_json", "_spin_rate_rpm", b"_spin_rate_rpm", "_start_speed_mph", b"_start_speed_mph", "_strikes", b"_strikes", "at_bat_index", b"at_bat_index", "balls", b"balls", "batter_id", b"batter_id", "batter_name", b"batter_name", "call_code", b"call_code", "call_description", b"call_description", "end_speed_mph", b"end_speed_mph", "inning", b"inning", "inning_half", b"inning_half", "is_ball", b"is_ball", "is_in_play", b"is_in_play", "is_strike", b"is_strike", "outs", b"outs", "pitch_number", b"pitch_number", "pitch_type", b"pitch_type", "pitch_type_description", b"pitch_type_description", "pitcher_id", b"pitcher_id", "pitcher_name", b"pitcher_name", "raw_payload_json", b"raw_payload_json", "spin_rate_rpm", b"spin_rate_rpm", "spine", b"spine", "start_speed_mph", b"start_speed_mph", "strikes", b"strikes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__balls: _TypeAlias = _typing.Literal["balls"]  # noqa: Y015
    _WhichOneofArgType__balls: _TypeAlias = _typing.Literal["_balls", b"_balls"]  # noqa: Y015
    _WhichOneofReturnType__batter_id: _TypeAlias = _typing.Literal["batter_id"]  # noqa: Y015
    _WhichOneofArgType__batter_id: _TypeAlias = _typing.Literal["_batter_id", b"_batter_id"]  # noqa: Y015
    _WhichOneofReturnType__batter_name: _TypeAlias = _typing.Literal["batter_name"]  # noqa: Y015
    _WhichOneofArgType__batter_name: _TypeAlias = _typing.Literal["_batter_name", b"_batter_name"]  # noqa: Y015
    _WhichOneofReturnType__call_code: _TypeAlias = _typing.Literal["call_code"]  # noqa: Y015
    _WhichOneofArgType__call_code: _TypeAlias = _typing.Literal["_call_code", b"_call_code"]  # noqa: Y015
    _WhichOneofReturnType__call_description: _TypeAlias = _typing.Literal["call_description"]  # noqa: Y015
    _WhichOneofArgType__call_description: _TypeAlias = _typing.Literal["_call_description", b"_call_description"]  # noqa: Y015
    _WhichOneofReturnType__end_speed_mph: _TypeAlias = _typing.Literal["end_speed_mph"]  # noqa: Y015
    _WhichOneofArgType__end_speed_mph: _TypeAlias = _typing.Literal["_end_speed_mph", b"_end_speed_mph"]  # noqa: Y015
    _WhichOneofReturnType__inning: _TypeAlias = _typing.Literal["inning"]  # noqa: Y015
    _WhichOneofArgType__inning: _TypeAlias = _typing.Literal["_inning", b"_inning"]  # noqa: Y015
    _WhichOneofReturnType__inning_half: _TypeAlias = _typing.Literal["inning_half"]  # noqa: Y015
    _WhichOneofArgType__inning_half: _TypeAlias = _typing.Literal["_inning_half", b"_inning_half"]  # noqa: Y015
    _WhichOneofReturnType__is_ball: _TypeAlias = _typing.Literal["is_ball"]  # noqa: Y015
    _WhichOneofArgType__is_ball: _TypeAlias = _typing.Literal["_is_ball", b"_is_ball"]  # noqa: Y015
    _WhichOneofReturnType__is_in_play: _TypeAlias = _typing.Literal["is_in_play"]  # noqa: Y015
    _WhichOneofArgType__is_in_play: _TypeAlias = _typing.Literal["_is_in_play", b"_is_in_play"]  # noqa: Y015
    _WhichOneofReturnType__is_strike: _TypeAlias = _typing.Literal["is_strike"]  # noqa: Y015
    _WhichOneofArgType__is_strike: _TypeAlias = _typing.Literal["_is_strike", b"_is_strike"]  # noqa: Y015
    _WhichOneofReturnType__outs: _TypeAlias = _typing.Literal["outs"]  # noqa: Y015
    _WhichOneofArgType__outs: _TypeAlias = _typing.Literal["_outs", b"_outs"]  # noqa: Y015
    _WhichOneofReturnType__pitch_type: _TypeAlias = _typing.Literal["pitch_type"]  # noqa: Y015
    _WhichOneofArgType__pitch_type: _TypeAlias = _typing.Literal["_pitch_type", b"_pitch_type"]  # noqa: Y015
    _WhichOneofReturnType__pitch_type_description: _TypeAlias = _typing.Literal["pitch_type_description"]  # noqa: Y015
    _WhichOneofArgType__pitch_type_description: _TypeAlias = _typing.Literal["_pitch_type_description", b"_pitch_type_description"]  # noqa: Y015
    _WhichOneofReturnType__pitcher_id: _TypeAlias = _typing.Literal["pitcher_id"]  # noqa: Y015
    _WhichOneofArgType__pitcher_id: _TypeAlias = _typing.Literal["_pitcher_id", b"_pitcher_id"]  # noqa: Y015
    _WhichOneofReturnType__pitcher_name: _TypeAlias = _typing.Literal["pitcher_name"]  # noqa: Y015
    _WhichOneofArgType__pitcher_name: _TypeAlias = _typing.Literal["_pitcher_name", b"_pitcher_name"]  # noqa: Y015
    _WhichOneofReturnType__raw_payload_json: _TypeAlias = _typing.Literal["raw_payload_json"]  # noqa: Y015
    _WhichOneofArgType__raw_payload_json: _TypeAlias = _typing.Literal["_raw_payload_json", b"_raw_payload_json"]  # noqa: Y015
    _WhichOneofReturnType__spin_rate_rpm: _TypeAlias = _typing.Literal["spin_rate_rpm"]  # noqa: Y015
    _WhichOneofArgType__spin_rate_rpm: _TypeAlias = _typing.Literal["_spin_rate_rpm", b"_spin_rate_rpm"]  # noqa: Y015
    _WhichOneofReturnType__start_speed_mph: _TypeAlias = _typing.Literal["start_speed_mph"]  # noqa: Y015
    _WhichOneofArgType__start_speed_mph: _TypeAlias = _typing.Literal["_start_speed_mph", b"_start_speed_mph"]  # noqa: Y015
    _WhichOneofReturnType__strikes: _TypeAlias = _typing.Literal["strikes"]  # noqa: Y015
    _WhichOneofArgType__strikes: _TypeAlias = _typing.Literal["_strikes", b"_strikes"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__balls) -> _WhichOneofReturnType__balls | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__batter_id) -> _WhichOneofReturnType__batter_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__batter_name) -> _WhichOneofReturnType__batter_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__call_code) -> _WhichOneofReturnType__call_code | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__call_description) -> _WhichOneofReturnType__call_description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__end_speed_mph) -> _WhichOneofReturnType__end_speed_mph | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__inning) -> _WhichOneofReturnType__inning | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__inning_half) -> _WhichOneofReturnType__inning_half | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_ball) -> _WhichOneofReturnType__is_ball | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_in_play) -> _WhichOneofReturnType__is_in_play | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__is_strike) -> _WhichOneofReturnType__is_strike | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__outs) -> _WhichOneofReturnType__outs | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pitch_type) -> _WhichOneofReturnType__pitch_type | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pitch_type_description) -> _WhichOneofReturnType__pitch_type_description | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pitcher_id) -> _WhichOneofReturnType__pitcher_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__pitcher_name) -> _WhichOneofReturnType__pitcher_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__raw_payload_json) -> _WhichOneofReturnType__raw_payload_json | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__spin_rate_rpm) -> _WhichOneofReturnType__spin_rate_rpm | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__start_speed_mph) -> _WhichOneofReturnType__start_speed_mph | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__strikes) -> _WhichOneofReturnType__strikes | None: ...

Global___MLBPitch: _TypeAlias = MLBPitch  # noqa: Y015

@_typing.final
class MLBGameState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPINE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    HOME_TEAM_FIELD_NUMBER: _builtins.int
    AWAY_TEAM_FIELD_NUMBER: _builtins.int
    HOME_SCORE_FIELD_NUMBER: _builtins.int
    AWAY_SCORE_FIELD_NUMBER: _builtins.int
    INNING_FIELD_NUMBER: _builtins.int
    INNING_HALF_FIELD_NUMBER: _builtins.int
    RAW_PAYLOAD_JSON_FIELD_NUMBER: _builtins.int
    status: _builtins.str
    home_team: _builtins.str
    away_team: _builtins.str
    home_score: _builtins.int
    away_score: _builtins.int
    inning: _builtins.int
    inning_half: _builtins.str
    raw_payload_json: _builtins.str
    @_builtins.property
    def spine(self) -> Global___Spine: ...
    def __init__(
        self,
        *,
        spine: Global___Spine | None = ...,
        status: _builtins.str | None = ...,
        home_team: _builtins.str | None = ...,
        away_team: _builtins.str | None = ...,
        home_score: _builtins.int | None = ...,
        away_score: _builtins.int | None = ...,
        inning: _builtins.int | None = ...,
        inning_half: _builtins.str | None = ...,
        raw_payload_json: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_away_score", b"_away_score", "_away_team", b"_away_team", "_home_score", b"_home_score", "_home_team", b"_home_team", "_inning", b"_inning", "_inning_half", b"_inning_half", "_raw_payload_json", b"_raw_payload_json", "_status", b"_status", "away_score", b"away_score", "away_team", b"away_team", "home_score", b"home_score", "home_team", b"home_team", "inning", b"inning", "inning_half", b"inning_half", "raw_payload_json", b"raw_payload_json", "spine", b"spine", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_away_score", b"_away_score", "_away_team", b"_away_team", "_home_score", b"_home_score", "_home_team", b"_home_team", "_inning", b"_inning", "_inning_half", b"_inning_half", "_raw_payload_json", b"_raw_payload_json", "_status", b"_status", "away_score", b"away_score", "away_team", b"away_team", "home_score", b"home_score", "home_team", b"home_team", "inning", b"inning", "inning_half", b"inning_half", "raw_payload_json", b"raw_payload_json", "spine", b"spine", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__away_score: _TypeAlias = _typing.Literal["away_score"]  # noqa: Y015
    _WhichOneofArgType__away_score: _TypeAlias = _typing.Literal["_away_score", b"_away_score"]  # noqa: Y015
    _WhichOneofReturnType__away_team: _TypeAlias = _typing.Literal["away_team"]  # noqa: Y015
    _WhichOneofArgType__away_team: _TypeAlias = _typing.Literal["_away_team", b"_away_team"]  # noqa: Y015
    _WhichOneofReturnType__home_score: _TypeAlias = _typing.Literal["home_score"]  # noqa: Y015
    _WhichOneofArgType__home_score: _TypeAlias = _typing.Literal["_home_score", b"_home_score"]  # noqa: Y015
    _WhichOneofReturnType__home_team: _TypeAlias = _typing.Literal["home_team"]  # noqa: Y015
    _WhichOneofArgType__home_team: _TypeAlias = _typing.Literal["_home_team", b"_home_team"]  # noqa: Y015
    _WhichOneofReturnType__inning: _TypeAlias = _typing.Literal["inning"]  # noqa: Y015
    _WhichOneofArgType__inning: _TypeAlias = _typing.Literal["_inning", b"_inning"]  # noqa: Y015
    _WhichOneofReturnType__inning_half: _TypeAlias = _typing.Literal["inning_half"]  # noqa: Y015
    _WhichOneofArgType__inning_half: _TypeAlias = _typing.Literal["_inning_half", b"_inning_half"]  # noqa: Y015
    _WhichOneofReturnType__raw_payload_json: _TypeAlias = _typing.Literal["raw_payload_json"]  # noqa: Y015
    _WhichOneofArgType__raw_payload_json: _TypeAlias = _typing.Literal["_raw_payload_json", b"_raw_payload_json"]  # noqa: Y015
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__away_score) -> _WhichOneofReturnType__away_score | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__away_team) -> _WhichOneofReturnType__away_team | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__home_score) -> _WhichOneofReturnType__home_score | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__home_team) -> _WhichOneofReturnType__home_team | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__inning) -> _WhichOneofReturnType__inning | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__inning_half) -> _WhichOneofReturnType__inning_half | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__raw_payload_json) -> _WhichOneofReturnType__raw_payload_json | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___MLBGameState: _TypeAlias = MLBGameState  # noqa: Y015
